name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npm run build  # This will run the build script in package.json

      - name: Start the application
        run: npm start  # This will start the application using the start script in package.json

